version: '3'

networks:
  default:
    external:
      name: ces-brnet

services:

  neo4j-core1:
    image: neo4j:3.4-enterprise
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - $HOME/devel/dbs/neo4j-core1/conf:/conf
      - $HOME/devel/dbs/neo4j-core1/data:/data
      - $HOME/devel/dbs/neo4j-core1/logs:/logs
    environment:
      #- NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:7473
      - NEO4J_dbms_connector_bolt_listen__address=:7687

  neo4j-core2:
    image: neo4j:3.4-enterprise
    ports:
      - 8474:8474
      - 8473:8473
      - 8687:8687
    volumes:
      - $HOME/devel/dbs/neo4j-core2/conf:/conf
      - $HOME/devel/dbs/neo4j-core2/data:/data
      - $HOME/devel/dbs/neo4j-core2/logs:/logs
    environment:
      #- NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:8474
      - NEO4J_dbms_connector_https_listen__address=:8473
      - NEO4J_dbms_connector_bolt_listen__address=:8687

  neo4j-core3:
    image: neo4j:3.4-enterprise
    ports:
      - 9474:9474
      - 9473:9473
      - 9687:9687
    volumes:
      - $HOME/devel/dbs/neo4j-core3/conf:/conf
      - $HOME/devel/dbs/neo4j-core3/data:/data
      - $HOME/devel/dbs/neo4j-core3/logs:/logs
    environment:
      #- NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:9474
      - NEO4J_dbms_connector_https_listen__address=:9473
      - NEO4J_dbms_connector_bolt_listen__address=:9687

  #neo4j-read1:
  #  image: neo4j:3.4-enterprise
  #  ports:
  #    - 1474:1474
  #    - 1473:1473
  #    - 1687:1687
  #  volumes:
  #    - $HOME/devel/dbs/neo4j-read1/conf:/conf
  #    - $HOME/devel/dbs/neo4j-read1/data:/data
  #    - $HOME/devel/dbs/neo4j-read1/logs:/logs
  #  environment:
  #    #- NEO4J_AUTH=neo4j/changeme
  #    - NEO4J_dbms_mode=READ_REPLICA
  #    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  #    - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
  #    - NEO4J_dbms_connector_http_listen__address=:1474
  #    - NEO4J_dbms_connector_https_listen__address=:1473
  #    - NEO4J_dbms_connector_bolt_listen__address=:1687